### ISSUE TITLE
Code release about the applications

### ISSUE THREAD

**Issue by HYLee1008** [ZhengdiYu/Arbitrary-Hands-3D-Reconstruction#11]
Hi! Thanks for your great work!

Can you release the code about your applications? I want to apply it to my own .fbx character.

**Comment by ZhengdiYu** [comment]
Sorry for my delay in response due to my work here. The applications are done in UE and Blender. The character-driven code for Blender will be released soon.

Take the Blender version as an example: Basically, you can use the MANO/SMPL parameters as the rotation angle and you will have to make sure the .fbx character's skeleton is aligned with SMPL-X's skeleton. You can either try to rig it with mixamo, or manually change the output to match with your .fbx character's skeleton

**Comment by leishengsheng** [comment]
> 所有者

你好啊，什么时候发布角色驱动代码吗
